### ISSUE TITLE
Provide finer control over the "phases" of a bundle deployment

### ISSUE THREAD

**Issue by luis-ochoa** [arcxp/deploy-action#1]
We have just implemented this action and found that while it works fine, for certain environments we would like finer control on the phases of deployment. For example, for production, we would like only to upload the bundle but not deploy it or promote it.

If we could have an action, e.g. `arcxp/upload-action` that would be ideal.

Another option would be using this same `arcxp/deploy-action` with an extra parameter, like `upload-only: true` (which can default to `false` and behave as it does right now, would work

**Comment by manchicken** [comment]
@luis-ochoa, without disclosing any sensitive internal information, can you help me understand the use case? I want to make sure that I keep your use case in mind as I think through this issue.

**Comment by luis-ochoa** [comment]
Sure.
We want to control how _**far**_ to go into the deployment process depending on the environment we're deploying to.

For example:

| Env|      Action(s)|       Comment |
|--------------|-----------|------------|
| Development | upload->deploy->promote      | Current behavior of arcxp/deploy-action        |
| Sandbox| upload->deploy  | No way of doing just this currently|
| Staging      | upload->deploy  | No way of doing just this currently|
| Production      | upload  | No way of doing just this currently|

Then in GHA we could pass a parameter to `arcxp-deploy-action` (or use a different action altogether) to accomplish the behavior above depending on the environment we're deploying to

**Comment by manchicken** [comment]
This makes a bunch of sense, thanks for the explanation. I'm thinking that now for each of the deploy steps, I can add an input for that step, which defaults to `true`.

I think that'd look something like:

```yaml
      - name: Perform the deploy
        if: ${{ success() }}
        uses: arcxp/deploy-action@v1
        with:
          org-id: your-org-here
          api-key: "${{ secrets.YOUR_DEPLOYER_TOKEN_HERE }}"
          api-hostname: api.sandbox.your-org-here.arcpublishing.com
          bundle-prefix: action-demo-1
          deploy: false
          promote: false
```

This would disable `deploy` and `promote`. It'll throw an error if you say `deploy:false` but `promote:true`.

Does this sound it would meet your needs?
