### ISSUE TITLE
Getting error on action

### ISSUE THREAD

**Issue by luis-ochoa** [arcxp/deploy-action#3]
Parameters:
```
  with:
    org-id: ***
    api-key: ***
    api-hostname: ***
    bundle-prefix: ***
    pagebuilder-version: 3.3.7
    retry-delay: 15
    retry-count: 40
    deploy: true
    promote: true
    artifact: dist/fusion-bundle.zip
    minimum-running-versions: 7
```

Error:
```
Run arcxp/deploy-action@v1
Error: Unexpected token '<', "<html>
<h"... is not valid JSON
/home/runner/work/_actions/arcxp/deploy-action/v1/dist/index.cjs:22165
      if (newVersions[newVersions.length - 1] !== latestVersion) {
                                  ^

TypeError: Cannot read properties of undefined (reading 'length')
    at main (/home/runner/work/_actions/arcxp/deploy-action/v1/dist/index.cjs:22165:35)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```
